"""Pydantic models for alerts, transactions, and compliance rules."""

from datetime import datetime, timezone
from enum import Enum
from pydantic import BaseModel, Field


class Severity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertType(str, Enum):
    LARGE_TRANSFER = "large_transfer"
    VELOCITY_BREACH = "velocity_breach"
    SANCTIONED_ADDRESS = "sanctioned_address"
    ROUND_NUMBER = "round_number"
    RAPID_SUCCESSION = "rapid_succession"
    STRUCTURING = "structuring"
    DORMANT_ACCOUNT = "dormant_account"
    CROSS_TOKEN_WASH = "cross_token_wash"
    AI_FLAGGED = "ai_flagged"


class EnforcementAction(str, Enum):
    FREEZE = "freeze"
    WIPE = "wipe"
    KYC_REVOKE = "kyc_revoke"
    PAUSE = "pause"
    NONE = "none"


class TokenTransfer(BaseModel):
    """Represents a single HTS token transfer."""
    transaction_id: str
    token_id: str
    sender: str
    receiver: str
    amount: float
    timestamp: datetime
    memo: str = ""


class Alert(BaseModel):
    """Compliance alert generated by the system."""
    id: str = Field(default="", description="Auto-generated alert ID")
    alert_type: AlertType
    severity: Severity
    transaction: TokenTransfer
    description: str
    risk_score: float = Field(ge=0.0, le=1.0)
    recommended_action: EnforcementAction = EnforcementAction.NONE
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    resolved: bool = False
    ai_analysis: str = ""


class ComplianceRule(BaseModel):
    """A configurable compliance rule."""
    id: str
    name: str
    description: str
    enabled: bool = True
    alert_type: AlertType
    severity: Severity
    parameters: dict = Field(default_factory=dict)


class SystemStatus(BaseModel):
    """Overall system status."""
    status: str = "running"
    monitored_tokens: list[str] = Field(default_factory=list)
    total_alerts: int = 0
    unresolved_alerts: int = 0
    last_scan_at: datetime | None = None
    uptime_seconds: float = 0.0


class HbarTransfer(BaseModel):
    """Represents a single HBAR (crypto) transfer between accounts."""
    transaction_id: str
    sender: str
    receiver: str
    amount: int  # tinybars
    timestamp: datetime
    memo: str = ""


class NftTransfer(BaseModel):
    """Represents a single NFT transfer."""
    transaction_id: str
    token_id: str
    serial_number: int
    sender: str
    receiver: str
    timestamp: datetime
    memo: str = ""


class AccountTokenBalance(BaseModel):
    """Token balance for an account."""
    token_id: str
    balance: int
    decimals: int = 0


class RiskAssessment(BaseModel):
    """AI-generated risk assessment for a transaction."""
    risk_score: float = Field(ge=0.0, le=1.0)
    risk_level: Severity
    reasoning: str
    recommended_action: EnforcementAction
    flags: list[str] = Field(default_factory=list)
